### PR TITLE
Issues/66 81

### PR DESCRIPTION
**Pull request by jump2conclusionsmatt**
This pull request is to resolve issues 66 and 81 - at least on the eLCI side. The function that maps emissions from the various NETL inventories to the federal elementary flow list (fedefl) will no use the mappings from the fedefl rather than the csv file previously contained in the data directory. This should close issue 66.

There is also a fix to issue 81 - flows with mapped UUIDs that do no exist are dropped from the final mapped dataframe to avoid populating openLCA with exchanges that will result in errors. The ultimate resolution to the problem will require updated mappings in the fedefl, so that no flows are dropped.

### CODE REVIEW

**Comment by jump2conclusionsmatt** [comment]
Hold of on merging this - I need to address one more issue with units. Right now, I think the dictionary processes don't properly account for the changing units.

**Comment by jump2conclusionsmatt** [comment]
Alright - this is ready to go now.
Along with the issues 66 and 81, this fixes a couple other things that I found while resolving these:
- There's new coal and natural gas data that doesn't need to be mapped to the fedefl because they're from models using the fedefl.
- There were two source of balancing authority names that resulted in some mismatches when going to link processes. Everything should eventually feed to the crosswalk provided in [BA_Codes_930.xlsx](https://github.com/USEPA/ElectricityLCI/blob/master/electricitylci/data/BA_Codes_930.xlsx)
- reducing the number of pd.concat info messages by adding sort=False to the concats I came across
- Correcting a UUID for methane in [hydro_upstream.py](https://github.com/USEPA/ElectricityLCI/blob/master/electricitylci/hydro_upstream.py)
- Fixing some shortcuts I had taken regarding units and conversion factors for mapping flows.

**Comment by bl-young** [comment]
@jump2conclusionsmatt we are trying to test the new flow mappings, but are having some issues. Did you commit coal_mining_lci.csv

**Comment by jump2conclusionsmatt** [comment]
I had not committed the new coal mining data yet. Should be up now. Checking to see if I missed any other data files.

**Comment by WesIngwersen** [comment]
With commit #505aae9 I modified setup.py to force install of a specific release of fedelemflowlist upon pip install. We should make sure that's the release that contains all the necessary mappings. @jump2conclusionsmatt @bl-young

**Comment by bl-young** [comment]
We are currently testing the mapping file from this branch so we should have a final version to push to FEDEFL in the next couple of days (cc @hottleta)

**Comment by WesIngwersen** [comment]
I'm good with merging in this major update to the upstream data when you've checked it

**Pull request merged**
