### PR TITLE
resolving conflict in combinator.py

### PR DESCRIPTION
**Pull request by bl-young**
Conversions and unit matching are done within the eLCI mapping file so this stretch of code is not needed and will throw errors.

### CODE REVIEW

**Comment by bl-young** [comment]
@jump2conclusionsmatt I didn't see that you had resolved this (#95) so created this pull request

**Comment by jump2conclusionsmatt** [comment]
Yeah, I was going to try and just revert this file to the previous commit. This works too. Have you run it after this change?

**Comment by bl-young** [comment]
I ran it successfully within combinator.py but didn't actually try the full run. Will give it a shot just to confirm.

**Comment by bl-young** [comment]
Ok I was able to complete the model build and import using eLCI-1. Good to go

**Pull request merged**
