### PR TITLE
Update upstream metadata

### PR DESCRIPTION
**Pull request by bl-young**
-Updated upstream processes to show correct years for start date and end date
-Fixed typos
-Set default target year to the electricity_lci_target_year

### CODE REVIEW

**Comment by bl-young** [comment]
@jump2conclusionsmatt Please double check. Given comments on metadata for the upstream systems, wanted to make sure they were consistent with eLCI; so updated metadata for coal, gas, and oil to reflect 2016 as the data year.

**Comment by bl-young** [comment]
The changes I made were causing an exception? No i wasn't having any issues.
Re: current year, I'm not sure I completely track how that year variable is used, given that the generation and emissions data is running from 2016 in most cases from eGRID, right?

**Comment by jump2conclusionsmatt** [comment]
Oh I see, these didn't exist before: `ar["validUntil"] = "12/31/"+targetyear`  - they were just statically set to 2018. I looked at the commits out of order I guess.

Yeah, most everything is tied to 2016, and 2018 used to be relevant. I guess we'll just keep it for now, but it's a bit weird. I'm just not sure how to update it. Should it be whatever year the user chooses for that target date?

**Comment by jump2conclusionsmatt** [comment]
Just finished running this, and my coal extraction UPs still have 2018 for the year in Time->Start date and End date. That's where these valid dates are supposed to show up, correct? I'll have to look later at why it's happenin.

**Comment by jump2conclusionsmatt** [comment]
And it didn't show 2016 because I never actually fetched your branch I guess. Anyhow, everything seems to be working. Reviewed and approved!

**Pull request merged**
